{
 "title": "Control Plane",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane UP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})"
    }
   ]
  },
  {
   "title": "Crash looping Pods",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(increase(kube_pod_container_status_restarts_total[5m]) > 5)"
    }
   ]
  },
  {
   "title": "Max API Latency",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "ns",
   "valueName": "current",
   "targets": [
    {
     "expr": "max (rate(apiserver_request_latencies_summary_sum{verb!=\"WATCH\"}[5m]))  / \nmax (rate(apiserver_request_latencies_summary_count{verb!=\"WATCH\"}[5m]))"
    }
   ]
  },
  {
   "title": "API Calls Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"5..\"}[1h]))"
    }
   ]
  },
  { "title": "Control Plane", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "API Servers UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-apiservers\"} == 1) / count(up{job=\"kubernetes-apiservers\"})) * 100"
    }
   ]
  },
  {
   "title": "Kube DNS UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"kubernetes-pods\", kubernetes_pod_name=~\"kube-dns-.*\"} == 1) / (sum(kube_deployment_spec_replicas{deployment=\"kube-dns\"}) * 2)) * 100"
    }
   ]
  },
  {
   "title": "Weave Net UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"weave-net\"} == 1) / count(up{job=\"weave-net\"})) * 100"
    }
   ]
  },
  {
   "title": "Kubelets UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(up{job=\"cadvisor\"} == 1) / count(up{job=\"cadvisor\"})) * 100"
    }
   ]
  },
  {
   "title": "API Servers Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"kubernetes-apiservers\"})"
    }
   ]
  },
  {
   "title": "Kube DNS Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{pod=~\"kube-dns.*\",condition=\"true\"})"
    }
   ]
  },
  {
   "title": "Weave Net Pods",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"weave-net\"}) /2 "
    }
   ]
  },
  {
   "title": "Kubelets Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"cadvisor\"})"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(100 - (avg by (instance) (rate(node_cpu{mode=\"idle\"}[5m])) * 100)) / count(node_cpu{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)) / sum(node_memory_MemTotal)) * 100"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{device=~\"/dev/mapper/.*\",id=\"/\"}) / sum (container_fs_limit_bytes{device=~\"/dev/mapper/.*\",id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(node_filefd_allocated) / sum(node_filefd_maximum) * 100"
    }
   ]
  },
  {
   "title": "Pod Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (sum(kube_node_status_capacity_pods) - sum(kube_pod_info)) / sum(kube_node_status_capacity_pods) * 100"
    }
   ]
  },
  {
   "title": "Pods Running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_pod_status_ready{condition=\"true\"} == 1)"
    }
   ]
  },
  {
   "title": "Pods Stopped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum ( count (kube_pod_status_ready == 1) - count (kube_pod_status_ready{condition=\"true\"} == 1))"
    }
   ]
  },
  {
   "title": "Pods Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count (kube_deployment_status_replicas_unavailable == 1)"
    }
   ]
  },
  { "title": "APIs Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Kubernetes API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (rate(apiserver_request_count{code!=\"0\"}[5m]))",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Kubernetes API Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "max by (resource, verb) (rate(apiserver_request_latencies_summary_sum{verb!~\"WATCH|CONNECT\"}[5m]))  / \nmax by (resource, verb) (rate(apiserver_request_latencies_summary_count{verb!~\"WATCH|CONNECT\"}[5m]))\n> 10",
     "legendFormat": "{{ resource }} {{ verb }}"
    }
   ]
  },
  {
   "title": "Docker API",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (rate (kubelet_docker_operations_errors[1m]))  by (operation_type) *100",
     "legendFormat": "{{ operation_type }}"
    }
   ]
  }
 ]
}